### ISSUE TITLE
Chef-solo startup error in resources/write.rb

### ISSUE THREAD

**Issue by davidc-donorschoose** [spheromak/sysctl-cookbook#1]
I love your sysctl LWRP, but something bad happened when you broke out sysctl into its own repo. After forking this repo, I cannot start up chef-solo at all. If I remove your resources/write.rb file, I can use your cookbook as I always had.

This is the contents of the stacktrace:

```
NoMethodError: undefined method `action' for #<Class:0xb74118a8>
/var/chef-solo/cookbooks/sysctl/resources/write.rb:2:in `class_from_file'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:581:in `build_from_file'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:542:in `initialize'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:542:in `new'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:542:in `build_from_file'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:96:in `load_lwrp_resources'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:120:in `call'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:120:in `foreach_cookbook_load_segment'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:119:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:119:in `foreach_cookbook_load_segment'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:117:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:117:in `foreach_cookbook_load_segment'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:94:in `load_lwrp_resources'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/run_context.rb:59:in `load'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:199:in `setup_run_context'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:162:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:207:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in `loop'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application.rb:70:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/chef-solo:25
/usr/bin/chef-solo:19:in `load'
```

**Comment by spheromak** [comment]
oh yea this is a bug i fixed local but didn't push up. ill get that pushed here quick
